### PR TITLE
Some improvements for MacOS

### PR DESCRIPTION
**Pull request by maximkrouk**
- NSVisualEffectView.state is now always active, so blur is rendered even if the app is not active.
- Blending mode changed to `.behindWindow` for such a fix:
<p>
Before:
Screen Shot 2020-06-27 at 15 56 57
After:
Screen Shot 2020-06-27 at 15 57 45
</p>

Now there is a problem with corner radius for blurred materials (`.windowBackground` works nice for example, but blurred `.underWindowBackground` doesn't 😢)

### CODE REVIEW

**Comment by twostraws** [comment]
Awesome – thank you! Quick question: are you saying the blurring is now always active and wasn't always active before? My understanding was that blur state is used to signal a window's active state.

**Comment by maximkrouk** [comment]
Here is the example without `visualEffectView.state = .active`. Maybe it worth to be a part of API to let developers decide if blur should be always active or not, but in my case this behavior doesn't look good.

ezgif com-video-to-gif

**Comment by twostraws** [comment]
Sorry to sound dim, but is that picture showing what happens right now, or what happens with your change?

**Comment by maximkrouk** [comment]
No problem. The picture is showing what happens right now, and this PR makes blur consistently active (due to `visualEffectView.state = .active` instead of `.followsWindowActiveState` which is default).

**Comment by twostraws** [comment]
Ah, I see. So, the behavior you're seeing right now is the default, recommended behavior in macOS – it's the same thing you'll see in the visual effect views in Finder and Xcode, for example. I'm happy to add an override, but I don't think it should be the default.

**Comment by maximkrouk** [comment]
Okay, so what do you think about adding an initializer with blending mode & state with default values to support both behaviors (with the old ones as default)

**Comment by twostraws** [comment]
If you can extend the existing initializer to provide these as an option, while retaining the current default behavior, that would be perfect 👌

**Comment by maximkrouk** [comment]
Done 🙂

**Comment by maximkrouk** [comment]
Also, I made the initializer public to solve [that issue](https://github.com/twostraws/VisualEffects/issues/5)

**Comment by twostraws** [comment]
Thank you!

**Pull request merged**
